//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadAndWrite
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reports
    {
        public int ReportId { get; set; }
        public int ReporterId { get; set; }
        public string TargetType { get; set; }
        public int TargetId { get; set; }
        public string Reason { get; set; }
        public string Status { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
